-- Seed skill suggestions
INSERT INTO public.skill_suggestions (key, locale, label, popularity)
VALUES
  ('communication', 'en', 'Communication', 0),
  ('communication', 'tr', 'İletişim', 0),
  ('written-communication', 'en', 'Written Communication', 0),
  ('written-communication', 'tr', 'Yazılı İletişim', 0),
  ('verbal-communication', 'en', 'Verbal Communication', 0),
  ('verbal-communication', 'tr', 'Sözlü İletişim', 0),
  ('presentation-skills', 'en', 'Presentation Skills', 0),
  ('presentation-skills', 'tr', 'Sunum Becerileri', 0),
  ('public-speaking', 'en', 'Public Speaking', 0),
  ('public-speaking', 'tr', 'Topluluk Önünde Konuşma', 0),
  ('negotiation', 'en', 'Negotiation', 0),
  ('negotiation', 'tr', 'Müzakere', 0),
  ('conflict-resolution', 'en', 'Conflict Resolution', 0),
  ('conflict-resolution', 'tr', 'Çatışma Çözümü', 0),
  ('time-management', 'en', 'Time Management', 0),
  ('time-management', 'tr', 'Zaman Yönetimi', 0),
  ('problem-solving', 'en', 'Problem Solving', 0),
  ('problem-solving', 'tr', 'Problem Çözme', 0),
  ('critical-thinking', 'en', 'Critical Thinking', 0),
  ('critical-thinking', 'tr', 'Eleştirel Düşünme', 0),
  ('analytical-thinking', 'en', 'Analytical Thinking', 0),
  ('analytical-thinking', 'tr', 'Analitik Düşünme', 0),
  ('decision-making', 'en', 'Decision Making', 0),
  ('decision-making', 'tr', 'Karar Verme', 0),
  ('teamwork', 'en', 'Teamwork', 0),
  ('teamwork', 'tr', 'Takım Çalışması', 0),
  ('leadership', 'en', 'Leadership', 0),
  ('leadership', 'tr', 'Liderlik', 0),
  ('mentoring', 'en', 'Mentoring', 0),
  ('mentoring', 'tr', 'Mentorluk', 0),
  ('coaching', 'en', 'Coaching', 0),
  ('coaching', 'tr', 'Koçluk', 0),
  ('stakeholder-management', 'en', 'Stakeholder Management', 0),
  ('stakeholder-management', 'tr', 'Paydaş Yönetimi', 0),
  ('customer-empathy', 'en', 'Customer Empathy', 0),
  ('customer-empathy', 'tr', 'Müşteri Empatisi', 0),
  ('adaptability', 'en', 'Adaptability', 0),
  ('adaptability', 'tr', 'Uyum Sağlama', 0),
  ('attention-to-detail', 'en', 'Attention to Detail', 0),
  ('attention-to-detail', 'tr', 'Detaylara Dikkat', 0),
  ('creativity', 'en', 'Creativity', 0),
  ('creativity', 'tr', 'Yaratıcılık', 0),
  ('strategic-thinking', 'en', 'Strategic Thinking', 0),
  ('strategic-thinking', 'tr', 'Stratejik Düşünme', 0),
  ('research', 'en', 'Research', 0),
  ('research', 'tr', 'Araştırma', 0),
  ('documentation', 'en', 'Documentation', 0),
  ('documentation', 'tr', 'Dokümantasyon', 0),
  ('process-improvement', 'en', 'Process Improvement', 0),
  ('process-improvement', 'tr', 'Süreç İyileştirme', 0),
  ('quality-assurance', 'en', 'Quality Assurance', 0),
  ('quality-assurance', 'tr', 'Kalite Güvence', 0),
  ('compliance', 'en', 'Compliance', 0),
  ('compliance', 'tr', 'Uyumluluk', 0),
  ('project-management', 'en', 'Project Management', 0),
  ('project-management', 'tr', 'Proje Yönetimi', 0),
  ('program-management', 'en', 'Program Management', 0),
  ('program-management', 'tr', 'Program Yönetimi', 0),
  ('product-management', 'en', 'Product Management', 0),
  ('product-management', 'tr', 'Ürün Yönetimi', 0),
  ('roadmapping', 'en', 'Roadmapping', 0),
  ('roadmapping', 'tr', 'Yol Haritası', 0),
  ('agile', 'en', 'Agile', 0),
  ('agile', 'tr', 'Agile', 0),
  ('scrum', 'en', 'Scrum', 0),
  ('scrum', 'tr', 'Scrum', 0),
  ('kanban', 'en', 'Kanban', 0),
  ('kanban', 'tr', 'Kanban', 0),
  ('jira', 'en', 'Jira', 0),
  ('jira', 'tr', 'Jira', 0),
  ('trello', 'en', 'Trello', 0),
  ('trello', 'tr', 'Trello', 0),
  ('asana', 'en', 'Asana', 0),
  ('asana', 'tr', 'Asana', 0),
  ('notion', 'en', 'Notion', 0),
  ('notion', 'tr', 'Notion', 0),
  ('okr', 'en', 'OKR', 0),
  ('okr', 'tr', 'OKR', 0),
  ('kpi-tracking', 'en', 'KPI Tracking', 0),
  ('kpi-tracking', 'tr', 'KPI Takibi', 0),
  ('risk-management', 'en', 'Risk Management', 0),
  ('risk-management', 'tr', 'Risk Yönetimi', 0),
  ('change-management', 'en', 'Change Management', 0),
  ('change-management', 'tr', 'Değişim Yönetimi', 0),
  ('budget-management', 'en', 'Budget Management', 0),
  ('budget-management', 'tr', 'Bütçe Yönetimi', 0),
  ('resource-planning', 'en', 'Resource Planning', 0),
  ('resource-planning', 'tr', 'Kaynak Planlama', 0),
  ('sales', 'en', 'Sales', 0),
  ('sales', 'tr', 'Satış', 0),
  ('b2b-sales', 'en', 'B2B Sales', 0),
  ('b2b-sales', 'tr', 'B2B Satış', 0),
  ('b2c-sales', 'en', 'B2C Sales', 0),
  ('b2c-sales', 'tr', 'B2C Satış', 0),
  ('cold-calling', 'en', 'Cold Calling', 0),
  ('cold-calling', 'tr', 'Soğuk Arama', 0),
  ('lead-generation', 'en', 'Lead Generation', 0),
  ('lead-generation', 'tr', 'Müşteri Adayı Üretme', 0),
  ('pipeline-management', 'en', 'Pipeline Management', 0),
  ('pipeline-management', 'tr', 'Satış Hunisi Yönetimi', 0),
  ('account-management', 'en', 'Account Management', 0),
  ('account-management', 'tr', 'Müşteri Hesabı Yönetimi', 0),
  ('crm', 'en', 'CRM', 0),
  ('crm', 'tr', 'CRM', 0),
  ('salesforce', 'en', 'Salesforce', 0),
  ('salesforce', 'tr', 'Salesforce', 0),
  ('hubspot', 'en', 'HubSpot', 0),
  ('hubspot', 'tr', 'HubSpot', 0),
  ('deal-closing', 'en', 'Deal Closing', 0),
  ('deal-closing', 'tr', 'Satış Kapatma', 0),
  ('upselling', 'en', 'Upselling', 0),
  ('upselling', 'tr', 'Yukarı Satış', 0),
  ('cross-selling', 'en', 'Cross-selling', 0),
  ('cross-selling', 'tr', 'Çapraz Satış', 0),
  ('customer-success', 'en', 'Customer Success', 0),
  ('customer-success', 'tr', 'Müşteri Başarısı', 0),
  ('retention', 'en', 'Retention', 0),
  ('retention', 'tr', 'Müşteri Tutma', 0),
  ('churn-analysis', 'en', 'Churn Analysis', 0),
  ('churn-analysis', 'tr', 'Churn Analizi', 0),
  ('marketing', 'en', 'Marketing', 0),
  ('marketing', 'tr', 'Pazarlama', 0),
  ('digital-marketing', 'en', 'Digital Marketing', 0),
  ('digital-marketing', 'tr', 'Dijital Pazarlama', 0),
  ('content-marketing', 'en', 'Content Marketing', 0),
  ('content-marketing', 'tr', 'İçerik Pazarlaması', 0),
  ('seo', 'en', 'SEO', 0),
  ('seo', 'tr', 'SEO', 0),
  ('sem', 'en', 'SEM', 0),
  ('sem', 'tr', 'SEM', 0),
  ('google-ads', 'en', 'Google Ads', 0),
  ('google-ads', 'tr', 'Google Ads', 0),
  ('meta-ads', 'en', 'Meta Ads', 0),
  ('meta-ads', 'tr', 'Meta Ads', 0),
  ('email-marketing', 'en', 'Email Marketing', 0),
  ('email-marketing', 'tr', 'E-posta Pazarlaması', 0),
  ('marketing-automation', 'en', 'Marketing Automation', 0),
  ('marketing-automation', 'tr', 'Pazarlama Otomasyonu', 0),
  ('brand-management', 'en', 'Brand Management', 0),
  ('brand-management', 'tr', 'Marka Yönetimi', 0),
  ('social-media', 'en', 'Social Media', 0),
  ('social-media', 'tr', 'Sosyal Medya', 0),
  ('community-management', 'en', 'Community Management', 0),
  ('community-management', 'tr', 'Topluluk Yönetimi', 0),
  ('copywriting', 'en', 'Copywriting', 0),
  ('copywriting', 'tr', 'Metin Yazarlığı', 0),
  ('growth-marketing', 'en', 'Growth Marketing', 0),
  ('growth-marketing', 'tr', 'Growth Pazarlama', 0),
  ('performance-marketing', 'en', 'Performance Marketing', 0),
  ('performance-marketing', 'tr', 'Performans Pazarlaması', 0),
  ('market-research', 'en', 'Market Research', 0),
  ('market-research', 'tr', 'Pazar Araştırması', 0),
  ('human-resources', 'en', 'Human Resources', 0),
  ('human-resources', 'tr', 'İnsan Kaynakları', 0),
  ('recruiting', 'en', 'Recruiting', 0),
  ('recruiting', 'tr', 'İşe Alım', 0),
  ('talent-acquisition', 'en', 'Talent Acquisition', 0),
  ('talent-acquisition', 'tr', 'Yetenek Kazanımı', 0),
  ('onboarding', 'en', 'Onboarding', 0),
  ('onboarding', 'tr', 'Onboarding', 0),
  ('employee-relations', 'en', 'Employee Relations', 0),
  ('employee-relations', 'tr', 'Çalışan İlişkileri', 0),
  ('compensation', 'en', 'Compensation', 0),
  ('compensation', 'tr', 'Ücretlendirme', 0),
  ('payroll', 'en', 'Payroll', 0),
  ('payroll', 'tr', 'Bordro', 0),
  ('performance-management', 'en', 'Performance Management', 0),
  ('performance-management', 'tr', 'Performans Yönetimi', 0),
  ('learning-development', 'en', 'Learning & Development', 0),
  ('learning-development', 'tr', 'Eğitim ve Gelişim', 0),
  ('hris', 'en', 'HRIS', 0),
  ('hris', 'tr', 'HRIS', 0),
  ('finance', 'en', 'Finance', 0),
  ('finance', 'tr', 'Finans', 0),
  ('accounting', 'en', 'Accounting', 0),
  ('accounting', 'tr', 'Muhasebe', 0),
  ('financial-reporting', 'en', 'Financial Reporting', 0),
  ('financial-reporting', 'tr', 'Finansal Raporlama', 0),
  ('financial-analysis', 'en', 'Financial Analysis', 0),
  ('financial-analysis', 'tr', 'Finansal Analiz', 0),
  ('budgeting', 'en', 'Budgeting', 0),
  ('budgeting', 'tr', 'Bütçeleme', 0),
  ('forecasting', 'en', 'Forecasting', 0),
  ('forecasting', 'tr', 'Tahminleme', 0),
  ('bookkeeping', 'en', 'Bookkeeping', 0),
  ('bookkeeping', 'tr', 'Ön Muhasebe', 0),
  ('audit', 'en', 'Audit', 0),
  ('audit', 'tr', 'Denetim', 0),
  ('tax', 'en', 'Tax', 0),
  ('tax', 'tr', 'Vergi', 0),
  ('cost-accounting', 'en', 'Cost Accounting', 0),
  ('cost-accounting', 'tr', 'Maliyet Muhasebesi', 0),
  ('fp-a', 'en', 'FP&A', 0),
  ('fp-a', 'tr', 'FP&A', 0),
  ('operations', 'en', 'Operations', 0),
  ('operations', 'tr', 'Operasyon', 0),
  ('process-design', 'en', 'Process Design', 0),
  ('process-design', 'tr', 'Süreç Tasarımı', 0),
  ('supply-chain', 'en', 'Supply Chain', 0),
  ('supply-chain', 'tr', 'Tedarik Zinciri', 0),
  ('logistics', 'en', 'Logistics', 0),
  ('logistics', 'tr', 'Lojistik', 0),
  ('inventory-management', 'en', 'Inventory Management', 0),
  ('inventory-management', 'tr', 'Stok Yönetimi', 0),
  ('procurement', 'en', 'Procurement', 0),
  ('procurement', 'tr', 'Satın Alma', 0),
  ('vendor-management', 'en', 'Vendor Management', 0),
  ('vendor-management', 'tr', 'Tedarikçi Yönetimi', 0),
  ('warehouse-management', 'en', 'Warehouse Management', 0),
  ('warehouse-management', 'tr', 'Depo Yönetimi', 0),
  ('fleet-management', 'en', 'Fleet Management', 0),
  ('fleet-management', 'tr', 'Filo Yönetimi', 0),
  ('customer-support', 'en', 'Customer Support', 0),
  ('customer-support', 'tr', 'Müşteri Destek', 0),
  ('call-center', 'en', 'Call Center', 0),
  ('call-center', 'tr', 'Çağrı Merkezi', 0),
  ('ticketing-systems', 'en', 'Ticketing Systems', 0),
  ('ticketing-systems', 'tr', 'Ticketing Sistemleri', 0),
  ('zendesk', 'en', 'Zendesk', 0),
  ('zendesk', 'tr', 'Zendesk', 0),
  ('intercom', 'en', 'Intercom', 0),
  ('intercom', 'tr', 'Intercom', 0),
  ('live-chat', 'en', 'Live Chat', 0),
  ('live-chat', 'tr', 'Canlı Destek', 0),
  ('service-level-agreements', 'en', 'Service Level Agreements', 0),
  ('service-level-agreements', 'tr', 'Hizmet Seviyesi Anlaşmaları', 0),
  ('design', 'en', 'Design', 0),
  ('design', 'tr', 'Tasarım', 0),
  ('graphic-design', 'en', 'Graphic Design', 0),
  ('graphic-design', 'tr', 'Grafik Tasarım', 0),
  ('ui-design', 'en', 'UI Design', 0),
  ('ui-design', 'tr', 'UI Tasarımı', 0),
  ('ux-design', 'en', 'UX Design', 0),
  ('ux-design', 'tr', 'UX Tasarımı', 0),
  ('user-research', 'en', 'User Research', 0),
  ('user-research', 'tr', 'Kullanıcı Araştırması', 0),
  ('wireframing', 'en', 'Wireframing', 0),
  ('wireframing', 'tr', 'Wireframe', 0),
  ('prototyping', 'en', 'Prototyping', 0),
  ('prototyping', 'tr', 'Prototipleme', 0),
  ('figma', 'en', 'Figma', 0),
  ('figma', 'tr', 'Figma', 0),
  ('adobe-photoshop', 'en', 'Adobe Photoshop', 0),
  ('adobe-photoshop', 'tr', 'Adobe Photoshop', 0),
  ('adobe-illustrator', 'en', 'Adobe Illustrator', 0),
  ('adobe-illustrator', 'tr', 'Adobe Illustrator', 0),
  ('adobe-xd', 'en', 'Adobe XD', 0),
  ('adobe-xd', 'tr', 'Adobe XD', 0),
  ('design-systems', 'en', 'Design Systems', 0),
  ('design-systems', 'tr', 'Tasarım Sistemleri', 0),
  ('brand-design', 'en', 'Brand Design', 0),
  ('brand-design', 'tr', 'Marka Tasarımı', 0),
  ('visual-design', 'en', 'Visual Design', 0),
  ('visual-design', 'tr', 'Görsel Tasarım', 0),
  ('healthcare', 'en', 'Healthcare', 0),
  ('healthcare', 'tr', 'Sağlık', 0),
  ('nursing', 'en', 'Nursing', 0),
  ('nursing', 'tr', 'Hemşirelik', 0),
  ('patient-care', 'en', 'Patient Care', 0),
  ('patient-care', 'tr', 'Hasta Bakımı', 0),
  ('medical-billing', 'en', 'Medical Billing', 0),
  ('medical-billing', 'tr', 'Tıbbi Faturalama', 0),
  ('medical-coding', 'en', 'Medical Coding', 0),
  ('medical-coding', 'tr', 'Tıbbi Kodlama', 0),
  ('pharmacy', 'en', 'Pharmacy', 0),
  ('pharmacy', 'tr', 'Eczacılık', 0),
  ('clinical-research', 'en', 'Clinical Research', 0),
  ('clinical-research', 'tr', 'Klinik Araştırma', 0),
  ('laboratory', 'en', 'Laboratory', 0),
  ('laboratory', 'tr', 'Laboratuvar', 0),
  ('education', 'en', 'Education', 0),
  ('education', 'tr', 'Eğitim', 0),
  ('teaching', 'en', 'Teaching', 0),
  ('teaching', 'tr', 'Öğretmenlik', 0),
  ('curriculum-development', 'en', 'Curriculum Development', 0),
  ('curriculum-development', 'tr', 'Müfredat Geliştirme', 0),
  ('instructional-design', 'en', 'Instructional Design', 0),
  ('instructional-design', 'tr', 'Öğretim Tasarımı', 0),
  ('classroom-management', 'en', 'Classroom Management', 0),
  ('classroom-management', 'tr', 'Sınıf Yönetimi', 0),
  ('assessment', 'en', 'Assessment', 0),
  ('assessment', 'tr', 'Ölçme Değerlendirme', 0),
  ('elearning', 'en', 'eLearning', 0),
  ('elearning', 'tr', 'e-Öğrenme', 0),
  ('legal', 'en', 'Legal', 0),
  ('legal', 'tr', 'Hukuk', 0),
  ('legal-research', 'en', 'Legal Research', 0),
  ('legal-research', 'tr', 'Hukuki Araştırma', 0),
  ('contract-management', 'en', 'Contract Management', 0),
  ('contract-management', 'tr', 'Sözleşme Yönetimi', 0),
  ('compliance-management', 'en', 'Compliance Management', 0),
  ('compliance-management', 'tr', 'Uyum Yönetimi', 0),
  ('corporate-law', 'en', 'Corporate Law', 0),
  ('corporate-law', 'tr', 'Şirketler Hukuku', 0),
  ('litigation', 'en', 'Litigation', 0),
  ('litigation', 'tr', 'Dava Takibi', 0),
  ('ip-law', 'en', 'IP Law', 0),
  ('ip-law', 'tr', 'Fikri Mülkiyet Hukuku', 0),
  ('retail', 'en', 'Retail', 0),
  ('retail', 'tr', 'Perakende', 0),
  ('merchandising', 'en', 'Merchandising', 0),
  ('merchandising', 'tr', 'Merchandising', 0),
  ('visual-merchandising', 'en', 'Visual Merchandising', 0),
  ('visual-merchandising', 'tr', 'Görsel Düzenleme', 0),
  ('store-operations', 'en', 'Store Operations', 0),
  ('store-operations', 'tr', 'Mağaza Operasyonları', 0),
  ('hospitality', 'en', 'Hospitality', 0),
  ('hospitality', 'tr', 'Konaklama', 0),
  ('front-office', 'en', 'Front Office', 0),
  ('front-office', 'tr', 'Ön Büro', 0),
  ('housekeeping', 'en', 'Housekeeping', 0),
  ('housekeeping', 'tr', 'Kat Hizmetleri', 0),
  ('food-beverage', 'en', 'Food & Beverage', 0),
  ('food-beverage', 'tr', 'Yiyecek & İçecek', 0),
  ('event-management', 'en', 'Event Management', 0),
  ('event-management', 'tr', 'Etkinlik Yönetimi', 0),
  ('manufacturing', 'en', 'Manufacturing', 0),
  ('manufacturing', 'tr', 'Üretim', 0),
  ('lean-manufacturing', 'en', 'Lean Manufacturing', 0),
  ('lean-manufacturing', 'tr', 'Yalın Üretim', 0),
  ('six-sigma', 'en', 'Six Sigma', 0),
  ('six-sigma', 'tr', 'Six Sigma', 0),
  ('quality-control', 'en', 'Quality Control', 0),
  ('quality-control', 'tr', 'Kalite Kontrol', 0),
  ('maintenance', 'en', 'Maintenance', 0),
  ('maintenance', 'tr', 'Bakım', 0),
  ('safety', 'en', 'Safety', 0),
  ('safety', 'tr', 'İş Güvenliği', 0),
  ('construction', 'en', 'Construction', 0),
  ('construction', 'tr', 'İnşaat', 0),
  ('project-scheduling', 'en', 'Project Scheduling', 0),
  ('project-scheduling', 'tr', 'Proje Zamanlama', 0),
  ('site-management', 'en', 'Site Management', 0),
  ('site-management', 'tr', 'Şantiye Yönetimi', 0),
  ('cost-estimation', 'en', 'Cost Estimation', 0),
  ('cost-estimation', 'tr', 'Maliyet Tahmini', 0),
  ('autocad', 'en', 'AutoCAD', 0),
  ('autocad', 'tr', 'AutoCAD', 0),
  ('data-analysis', 'en', 'Data Analysis', 0),
  ('data-analysis', 'tr', 'Veri Analizi', 0),
  ('excel', 'en', 'Excel', 0),
  ('excel', 'tr', 'Excel', 0),
  ('google-sheets', 'en', 'Google Sheets', 0),
  ('google-sheets', 'tr', 'Google Sheets', 0),
  ('power-bi', 'en', 'Power BI', 0),
  ('power-bi', 'tr', 'Power BI', 0),
  ('tableau', 'en', 'Tableau', 0),
  ('tableau', 'tr', 'Tableau', 0),
  ('sql', 'en', 'SQL', 0),
  ('sql', 'tr', 'SQL', 0),
  ('reporting', 'en', 'Reporting', 0),
  ('reporting', 'tr', 'Raporlama', 0),
  ('dashboards', 'en', 'Dashboards', 0),
  ('dashboards', 'tr', 'Dashboard', 0),
  ('statistics', 'en', 'Statistics', 0),
  ('statistics', 'tr', 'İstatistik', 0),
  ('product-analytics', 'en', 'Product Analytics', 0),
  ('product-analytics', 'tr', 'Ürün Analitiği', 0),
  ('a-b-testing', 'en', 'A/B Testing', 0),
  ('a-b-testing', 'tr', 'A/B Testi', 0),
  ('user-testing', 'en', 'User Testing', 0),
  ('user-testing', 'tr', 'Kullanıcı Testi', 0),
  ('survey-design', 'en', 'Survey Design', 0),
  ('survey-design', 'tr', 'Anket Tasarımı', 0),
  ('writing', 'en', 'Writing', 0),
  ('writing', 'tr', 'Yazma', 0),
  ('editing', 'en', 'Editing', 0),
  ('editing', 'tr', 'Editörlük', 0),
  ('proofreading', 'en', 'Proofreading', 0),
  ('proofreading', 'tr', 'Redaksiyon', 0),
  ('translation', 'en', 'Translation', 0),
  ('translation', 'tr', 'Çeviri', 0),
  ('photography', 'en', 'Photography', 0),
  ('photography', 'tr', 'Fotoğrafçılık', 0),
  ('video-editing', 'en', 'Video Editing', 0),
  ('video-editing', 'tr', 'Video Kurgu', 0),
  ('motion-design', 'en', 'Motion Design', 0),
  ('motion-design', 'tr', 'Motion Tasarım', 0),
  ('animation', 'en', 'Animation', 0),
  ('animation', 'tr', 'Animasyon', 0),
  ('sourcing', 'en', 'Sourcing', 0),
  ('sourcing', 'tr', 'Kaynak Bulma', 0),
  ('tender-management', 'en', 'Tender Management', 0),
  ('tender-management', 'tr', 'İhale Yönetimi', 0),
  ('customer-service', 'en', 'Customer Service', 0),
  ('customer-service', 'tr', 'Müşteri Hizmetleri', 0),
  ('complaint-management', 'en', 'Complaint Management', 0),
  ('complaint-management', 'tr', 'Şikayet Yönetimi', 0),
  ('call-handling', 'en', 'Call Handling', 0),
  ('call-handling', 'tr', 'Çağrı Yönetimi', 0),
  ('event-planning', 'en', 'Event Planning', 0),
  ('event-planning', 'tr', 'Etkinlik Planlama', 0),
  ('event-marketing', 'en', 'Event Marketing', 0),
  ('event-marketing', 'tr', 'Etkinlik Pazarlaması', 0),
  ('business-development', 'en', 'Business Development', 0),
  ('business-development', 'tr', 'İş Geliştirme', 0),
  ('partnerships', 'en', 'Partnerships', 0),
  ('partnerships', 'tr', 'İş Ortaklıkları', 0),
  ('go-to-market', 'en', 'Go-to-Market', 0),
  ('go-to-market', 'tr', 'Go-to-Market', 0),
  ('operations-management', 'en', 'Operations Management', 0),
  ('operations-management', 'tr', 'Operasyon Yönetimi', 0),
  ('facility-management', 'en', 'Facility Management', 0),
  ('facility-management', 'tr', 'Tesis Yönetimi', 0),
  ('hr-operations', 'en', 'HR Operations', 0),
  ('hr-operations', 'tr', 'İK Operasyonları', 0),
  ('people-analytics', 'en', 'People Analytics', 0),
  ('people-analytics', 'tr', 'İK Analitiği', 0),
  ('customer-journey-mapping', 'en', 'Customer Journey Mapping', 0),
  ('customer-journey-mapping', 'tr', 'Müşteri Yolculuğu Haritalama', 0),
  ('service-design', 'en', 'Service Design', 0),
  ('service-design', 'tr', 'Hizmet Tasarımı', 0),
  ('e-commerce', 'en', 'E-commerce', 0),
  ('e-commerce', 'tr', 'E-ticaret', 0),
  ('marketplace-management', 'en', 'Marketplace Management', 0),
  ('marketplace-management', 'tr', 'Pazar Yeri Yönetimi', 0),
  ('product-listing', 'en', 'Product Listing', 0),
  ('product-listing', 'tr', 'Ürün Listeleme', 0),
  ('logistics-planning', 'en', 'Logistics Planning', 0),
  ('logistics-planning', 'tr', 'Lojistik Planlama', 0),
  ('route-optimization', 'en', 'Route Optimization', 0),
  ('route-optimization', 'tr', 'Rota Optimizasyonu', 0),
  ('healthcare-compliance', 'en', 'Healthcare Compliance', 0),
  ('healthcare-compliance', 'tr', 'Sağlık Uyum', 0),
  ('patient-scheduling', 'en', 'Patient Scheduling', 0),
  ('patient-scheduling', 'tr', 'Hasta Randevu', 0),
  ('teaching-english', 'en', 'Teaching English', 0),
  ('teaching-english', 'tr', 'İngilizce Öğretimi', 0),
  ('early-childhood-education', 'en', 'Early Childhood Education', 0),
  ('early-childhood-education', 'tr', 'Okul Öncesi Eğitim', 0),
  ('legal-drafting', 'en', 'Legal Drafting', 0),
  ('legal-drafting', 'tr', 'Hukuki Metin Yazımı', 0),
  ('contract-drafting', 'en', 'Contract Drafting', 0),
  ('contract-drafting', 'tr', 'Sözleşme Yazımı', 0),
  ('hotel-management', 'en', 'Hotel Management', 0),
  ('hotel-management', 'tr', 'Otel Yönetimi', 0),
  ('restaurant-management', 'en', 'Restaurant Management', 0),
  ('restaurant-management', 'tr', 'Restoran Yönetimi', 0),
  ('inventory-control', 'en', 'Inventory Control', 0),
  ('inventory-control', 'tr', 'Stok Kontrol', 0),
  ('demand-planning', 'en', 'Demand Planning', 0),
  ('demand-planning', 'tr', 'Talep Planlama', 0),
  ('customer-experience', 'en', 'Customer Experience', 0),
  ('customer-experience', 'tr', 'Müşteri Deneyimi', 0),
  ('cx-strategy', 'en', 'CX Strategy', 0),
  ('cx-strategy', 'tr', 'CX Stratejisi', 0),
  ('account-receivable', 'en', 'Account Receivable', 0),
  ('account-receivable', 'tr', 'Alacaklar', 0),
  ('account-payable', 'en', 'Account Payable', 0),
  ('account-payable', 'tr', 'Borçlar', 0),
  ('budget-forecasting', 'en', 'Budget Forecasting', 0),
  ('budget-forecasting', 'tr', 'Bütçe Tahmini', 0),
  ('financial-modeling', 'en', 'Financial Modeling', 0),
  ('financial-modeling', 'tr', 'Finansal Modelleme', 0),
  ('operations-research', 'en', 'Operations Research', 0),
  ('operations-research', 'tr', 'Yöneylem Araştırması', 0),
  ('data-entry', 'en', 'Data Entry', 0),
  ('data-entry', 'tr', 'Veri Girişi', 0),
  ('customer-onboarding', 'en', 'Customer Onboarding', 0),
  ('customer-onboarding', 'tr', 'Müşteri Onboarding', 0),
  ('training', 'en', 'Training', 0),
  ('training', 'tr', 'Eğitim', 0),
  ('hr-policies', 'en', 'HR Policies', 0),
  ('hr-policies', 'tr', 'İK Politikaları', 0),
  ('employee-engagement', 'en', 'Employee Engagement', 0),
  ('employee-engagement', 'tr', 'Çalışan Bağlılığı', 0),
  ('risk-assessment', 'en', 'Risk Assessment', 0),
  ('risk-assessment', 'tr', 'Risk Değerlendirme', 0),
  ('health-safety', 'en', 'Health & Safety', 0),
  ('health-safety', 'tr', 'İş Sağlığı ve Güvenliği', 0),
  ('business-analysis', 'en', 'Business Analysis', 0),
  ('business-analysis', 'tr', 'İş Analizi', 0),
  ('requirements-gathering', 'en', 'Requirements Gathering', 0),
  ('requirements-gathering', 'tr', 'Gereksinim Toplama', 0),
  ('process-mapping', 'en', 'Process Mapping', 0),
  ('process-mapping', 'tr', 'Süreç Haritalama', 0),
  ('office-management', 'en', 'Office Management', 0),
  ('office-management', 'tr', 'Ofis Yönetimi', 0),
  ('administrative-support', 'en', 'Administrative Support', 0),
  ('administrative-support', 'tr', 'İdari Destek', 0),
  ('scheduling', 'en', 'Scheduling', 0),
  ('scheduling', 'tr', 'Takvim Yönetimi', 0),
  ('crm-administration', 'en', 'CRM Administration', 0),
  ('crm-administration', 'tr', 'CRM Yönetimi', 0),
  ('data-privacy', 'en', 'Data Privacy', 0),
  ('data-privacy', 'tr', 'Veri Gizliliği', 0),
  ('gdpr', 'en', 'GDPR', 0),
  ('gdpr', 'tr', 'KVKK/GDPR', 0),
  ('social-media-strategy', 'en', 'Social Media Strategy', 0),
  ('social-media-strategy', 'tr', 'Sosyal Medya Stratejisi', 0),
  ('content-strategy', 'en', 'Content Strategy', 0),
  ('content-strategy', 'tr', 'İçerik Stratejisi', 0),
  ('brand-strategy', 'en', 'Brand Strategy', 0),
  ('brand-strategy', 'tr', 'Marka Stratejisi', 0),
  ('public-relations', 'en', 'Public Relations', 0),
  ('public-relations', 'tr', 'Halkla İlişkiler', 0),
  ('media-relations', 'en', 'Media Relations', 0),
  ('media-relations', 'tr', 'Basın İlişkileri', 0),
  ('crisis-management', 'en', 'Crisis Management', 0),
  ('crisis-management', 'tr', 'Kriz Yönetimi', 0),
  ('store-management', 'en', 'Store Management', 0),
  ('store-management', 'tr', 'Mağaza Yönetimi', 0),
  ('fundraising', 'en', 'Fundraising', 0),
  ('fundraising', 'tr', 'Fon Toplama', 0),
  ('grant-writing', 'en', 'Grant Writing', 0),
  ('grant-writing', 'tr', 'Hibe Yazımı', 0),
  ('research-methods', 'en', 'Research Methods', 0),
  ('research-methods', 'tr', 'Araştırma Yöntemleri', 0),
  ('survey-analysis', 'en', 'Survey Analysis', 0),
  ('survey-analysis', 'tr', 'Anket Analizi', 0),
  ('copy-editing', 'en', 'Copy Editing', 0),
  ('copy-editing', 'tr', 'Metin Editörlüğü', 0),
  ('localization', 'en', 'Localization', 0),
  ('localization', 'tr', 'Yerelleştirme', 0),
  ('data-visualization', 'en', 'Data Visualization', 0),
  ('data-visualization', 'tr', 'Veri Görselleştirme', 0),
  ('storytelling', 'en', 'Storytelling', 0),
  ('storytelling', 'tr', 'Hikayeleştirme', 0),
  ('customer-retention', 'en', 'Customer Retention', 0),
  ('customer-retention', 'tr', 'Müşteri Tutma', 0),
  ('strategic-planning', 'en', 'Strategic Planning', 0),
  ('strategic-planning', 'tr', 'Stratejik Planlama', 0),
  ('business-strategy', 'en', 'Business Strategy', 0),
  ('business-strategy', 'tr', 'İş Stratejisi', 0),
  ('quality-management', 'en', 'Quality Management', 0),
  ('quality-management', 'tr', 'Kalite Yönetimi', 0),
  ('iso-standards', 'en', 'ISO Standards', 0),
  ('iso-standards', 'tr', 'ISO Standartları', 0),
  ('event-coordination', 'en', 'Event Coordination', 0),
  ('event-coordination', 'tr', 'Etkinlik Koordinasyonu', 0),
  ('vendor-coordination', 'en', 'Vendor Coordination', 0),
  ('vendor-coordination', 'tr', 'Tedarikçi Koordinasyonu', 0),
  ('brand-partnerships', 'en', 'Brand Partnerships', 0),
  ('brand-partnerships', 'tr', 'Marka İş Ortaklıkları', 0),
  ('influencer-marketing', 'en', 'Influencer Marketing', 0),
  ('influencer-marketing', 'tr', 'Influencer Pazarlaması', 0),
  ('customer-support-tools', 'en', 'Customer Support Tools', 0),
  ('customer-support-tools', 'tr', 'Müşteri Destek Araçları', 0),
  ('knowledge-base', 'en', 'Knowledge Base', 0),
  ('knowledge-base', 'tr', 'Bilgi Bankası', 0),
  ('operations-analytics', 'en', 'Operations Analytics', 0),
  ('operations-analytics', 'tr', 'Operasyon Analitiği', 0),
  ('service-operations', 'en', 'Service Operations', 0),
  ('service-operations', 'tr', 'Hizmet Operasyonları', 0),
  ('software-testing', 'en', 'Software Testing', 0),
  ('software-testing', 'tr', 'Yazılım Testi', 0),
  ('manual-testing', 'en', 'Manual Testing', 0),
  ('manual-testing', 'tr', 'Manuel Test', 0),
  ('automation-testing', 'en', 'Automation Testing', 0),
  ('automation-testing', 'tr', 'Otomasyon Testi', 0),
  ('basic-html', 'en', 'Basic HTML', 0),
  ('basic-html', 'tr', 'Temel HTML', 0),
  ('basic-css', 'en', 'Basic CSS', 0),
  ('basic-css', 'tr', 'Temel CSS', 0),
  ('microsoft-office', 'en', 'Microsoft Office', 0),
  ('microsoft-office', 'tr', 'Microsoft Office', 0),
  ('google-workspace', 'en', 'Google Workspace', 0),
  ('google-workspace', 'tr', 'Google Workspace', 0),
  ('javascript', 'en', 'JavaScript', 0),
  ('javascript', 'tr', 'JavaScript', 0),
  ('typescript', 'en', 'TypeScript', 0),
  ('typescript', 'tr', 'TypeScript', 0),
  ('python', 'en', 'Python', 0),
  ('python', 'tr', 'Python', 0),
  ('java', 'en', 'Java', 0),
  ('java', 'tr', 'Java', 0),
  ('c', 'en', 'C', 0),
  ('c', 'tr', 'C', 0),
  ('c', 'en', 'C++', 0),
  ('c', 'tr', 'C++', 0),
  ('c', 'en', 'C#', 0),
  ('c', 'tr', 'C#', 0),
  ('go', 'en', 'Go', 0),
  ('go', 'tr', 'Go', 0),
  ('rust', 'en', 'Rust', 0),
  ('rust', 'tr', 'Rust', 0),
  ('kotlin', 'en', 'Kotlin', 0),
  ('kotlin', 'tr', 'Kotlin', 0),
  ('swift', 'en', 'Swift', 0),
  ('swift', 'tr', 'Swift', 0),
  ('php', 'en', 'PHP', 0),
  ('php', 'tr', 'PHP', 0),
  ('ruby', 'en', 'Ruby', 0),
  ('ruby', 'tr', 'Ruby', 0),
  ('scala', 'en', 'Scala', 0),
  ('scala', 'tr', 'Scala', 0),
  ('dart', 'en', 'Dart', 0),
  ('dart', 'tr', 'Dart', 0),
  ('html', 'en', 'HTML', 0),
  ('html', 'tr', 'HTML', 0),
  ('css', 'en', 'CSS', 0),
  ('css', 'tr', 'CSS', 0),
  ('react', 'en', 'React', 0),
  ('react', 'tr', 'React', 0),
  ('next-js', 'en', 'Next.js', 0),
  ('next-js', 'tr', 'Next.js', 0),
  ('vue-js', 'en', 'Vue.js', 0),
  ('vue-js', 'tr', 'Vue.js', 0),
  ('angular', 'en', 'Angular', 0),
  ('angular', 'tr', 'Angular', 0),
  ('svelte', 'en', 'Svelte', 0),
  ('svelte', 'tr', 'Svelte', 0),
  ('node-js', 'en', 'Node.js', 0),
  ('node-js', 'tr', 'Node.js', 0),
  ('express', 'en', 'Express', 0),
  ('express', 'tr', 'Express', 0),
  ('nestjs', 'en', 'NestJS', 0),
  ('nestjs', 'tr', 'NestJS', 0),
  ('django', 'en', 'Django', 0),
  ('django', 'tr', 'Django', 0),
  ('flask', 'en', 'Flask', 0),
  ('flask', 'tr', 'Flask', 0),
  ('fastapi', 'en', 'FastAPI', 0),
  ('fastapi', 'tr', 'FastAPI', 0),
  ('spring-boot', 'en', 'Spring Boot', 0),
  ('spring-boot', 'tr', 'Spring Boot', 0),
  ('asp-net-core', 'en', 'ASP.NET Core', 0),
  ('asp-net-core', 'tr', 'ASP.NET Core', 0),
  ('laravel', 'en', 'Laravel', 0),
  ('laravel', 'tr', 'Laravel', 0),
  ('ruby-on-rails', 'en', 'Ruby on Rails', 0),
  ('ruby-on-rails', 'tr', 'Ruby on Rails', 0),
  ('postgresql', 'en', 'PostgreSQL', 0),
  ('postgresql', 'tr', 'PostgreSQL', 0),
  ('mysql', 'en', 'MySQL', 0),
  ('mysql', 'tr', 'MySQL', 0),
  ('mongodb', 'en', 'MongoDB', 0),
  ('mongodb', 'tr', 'MongoDB', 0),
  ('redis', 'en', 'Redis', 0),
  ('redis', 'tr', 'Redis', 0),
  ('docker', 'en', 'Docker', 0),
  ('docker', 'tr', 'Docker', 0),
  ('kubernetes', 'en', 'Kubernetes', 0),
  ('kubernetes', 'tr', 'Kubernetes', 0),
  ('aws', 'en', 'AWS', 0),
  ('aws', 'tr', 'AWS', 0),
  ('azure', 'en', 'Azure', 0),
  ('azure', 'tr', 'Azure', 0),
  ('google-cloud', 'en', 'Google Cloud', 0),
  ('google-cloud', 'tr', 'Google Cloud', 0),
  ('git', 'en', 'Git', 0),
  ('git', 'tr', 'Git', 0),
  ('ci-cd', 'en', 'CI/CD', 0),
  ('ci-cd', 'tr', 'CI/CD', 0),
  ('jenkins', 'en', 'Jenkins', 0),
  ('jenkins', 'tr', 'Jenkins', 0),
  ('github-actions', 'en', 'GitHub Actions', 0),
  ('github-actions', 'tr', 'GitHub Actions', 0),
  ('terraform', 'en', 'Terraform', 0),
  ('terraform', 'tr', 'Terraform', 0),
  ('linux', 'en', 'Linux', 0),
  ('linux', 'tr', 'Linux', 0),
  ('nginx', 'en', 'Nginx', 0),
  ('nginx', 'tr', 'Nginx', 0),
  ('graphql', 'en', 'GraphQL', 0),
  ('graphql', 'tr', 'GraphQL', 0),
  ('rest-api', 'en', 'REST API', 0),
  ('rest-api', 'tr', 'REST API', 0),
  ('grpc', 'en', 'gRPC', 0),
  ('grpc', 'tr', 'gRPC', 0),
  ('microservices', 'en', 'Microservices', 0),
  ('microservices', 'tr', 'Mikroservisler', 0),
  ('system-design', 'en', 'System Design', 0),
  ('system-design', 'tr', 'Sistem Tasarımı', 0),
  ('data-structures', 'en', 'Data Structures', 0),
  ('data-structures', 'tr', 'Veri Yapıları', 0),
  ('algorithms', 'en', 'Algorithms', 0),
  ('algorithms', 'tr', 'Algoritmalar', 0),
  ('testing', 'en', 'Testing', 0),
  ('testing', 'tr', 'Test', 0),
  ('unit-testing', 'en', 'Unit Testing', 0),
  ('unit-testing', 'tr', 'Birim Testi', 0),
  ('e2e-testing', 'en', 'E2E Testing', 0),
  ('e2e-testing', 'tr', 'Uçtan Uca Test', 0),
  ('tdd', 'en', 'TDD', 0),
  ('tdd', 'tr', 'TDD', 0),
  ('oop', 'en', 'OOP', 0),
  ('oop', 'tr', 'Nesne Yönelimli Programlama', 0),
  ('design-patterns', 'en', 'Design Patterns', 0),
  ('design-patterns', 'tr', 'Tasarım Kalıpları', 0),
  ('solid', 'en', 'SOLID', 0),
  ('solid', 'tr', 'SOLID', 0),
  ('clean-architecture', 'en', 'Clean Architecture', 0),
  ('clean-architecture', 'tr', 'Temiz Mimari', 0)
ON CONFLICT (key, locale) DO NOTHING;
